# NumPy Arrays


**Numpy provides:**

1. extension package to Python for multi-dimensional arrays
2. closer to hardware (efficiency)
3. designed for scientific computation (convenience)
4. Also known as array oriented computing

# 1. Creating arrays

A numpy array is a grid of values, all of the same type. The number of dimensions is the no of axes of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [2]:
#1-D array
import numpy as np

a = np.array([0, 1, 2, 3])

type(a)

numpy.ndarray

In [3]:
a.ndim       #prints no of exes 

1

In [8]:
a.shape      #tuple of integers indicating size of array in each dimension

(4,)

In [7]:
a.size       #total no of elements in the array (products of elements of shape)

4

In [5]:
a.dtype      #types of elements in the array  

dtype('int64')

In [6]:
a.itemsize   # the size in bytes of each element of the array

8

In [31]:
# 2-D, 3-D....

b = np.array([[0, 1, 2], [3, 4, 5]])

#print dimenstions
print(b.ndim)

#print shape of the array
print(b.shape)

2
(2, 3)


** 1.2  Functions for creating arrays**

In [10]:
#using arrange function

# arange is an array-valued version of the built-in Python range function

a = np.arange(10) # 0.... n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#using linspace

a = np.linspace(5, 10, 10) #start, end, number of points

a

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [12]:
#common arrays

a = np.ones([3, 3])

a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
b = np.zeros((3, 3))

b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
c = np.eye(4)  #Return a 2-D array with ones on the diagonal and zeros elsewhere.

c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
d = np.eye(3, 2) #3 is number of rows, 2 is number of columns, index of diagonal start with 0

d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [17]:
c = np.full((2,3), 5) # Create a constant array
c

array([[5, 5, 5],
       [5, 5, 5]])

In [13]:
#create array using diag function

a = np.diag([1, 2, 3, 4]) #construct a diagonal array.

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [14]:
#create array using random

#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a = np.random.rand(4) 

a

array([ 0.57944059,  0.4826708 ,  0.66348841,  0.37141847])

# 2. Basic DataTypes

You may have noticed that, in some instances, array elements are displayed with a **trailing dot (e.g. 2. vs 2)**. This is due to a difference in the **data-type** used:


In [20]:
a = np.arange(10)

print(a.dtype)

int64


In [8]:
#You can explicitly specify which data-type you want:

a = np.arange(10, dtype='float64')
print(a.dtype)
print(a)

float64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [17]:
#The default data type is float for zeros and ones function

a = np.zeros((3, 3))

print(a)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [19]:
d = np.array([1+2j, 2+4j])   #Complex datatype

print(d.dtype)

complex128


In [20]:
b = np.array([True, False, True, False])  #Boolean datatype

print(b.dtype)

bool


# Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array.

In [9]:

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("a =\n",a)
print(a[1][1])
print(a[1,1])

b = a[:2, 1:3]
print ("b =\n",b)

a =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
6
6
b =
 [[2 3]
 [6 7]]


We can also mix integer indexing with slice indexing. However, doing so will yield an array of lower dimension than the original array.
Mixing integer indexing with slices yields an array of lower dimension, while using only slices yields an array of the same dimension as the original array:

In [23]:

row_r1 = a[1, :]        
row_r2 = a[1:2, :] 
row_r3 = a[[1], :]  
print (row_r1)
print (row_r2)
print (row_r3)

[5 6 7 8]
[[5 6 7 8]]
[[5 6 7 8]]


Integer array indexing: It allows to construct arbitrary arrays using the data from another array. Here is an example:

In [4]:
a = np.array([[7,2], [8, 4], [5, 6]])

# An example of integer array indexing.
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[7 4 5]
[7 4 5]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix.

In [10]:
#2D array
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print("a=\n",a)

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of "a" using the indices in "b"
print("Selecting one element from each row : ",a[np.arange(4), b]) 

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print("Mutating/changing one element from each row\n",a)

a=
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Selecting one element from each row :  [ 1  6  7 11]
Mutating/changing one element from each row
 [[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


Boolean array indexing: It allows selection of array elements that satisfy some condition.

In [3]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a>2)

[[False False]
 [ True  True]
 [ True  True]]


In [53]:
a = np.array([[1,2], [3, 4], [5, 6]])

#find numbers greater than 2 in the array
b = (a > 2)


print(b)
print(a[b])

# We can do all of the above in a single concise statement:
print (a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


# Elementwise Operations

**1. Math Operations**

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module

In [28]:
x = np.array([[4,3],[2,4]], dtype=np.float64)
y = np.array([[1,6],[5,8]], dtype='float64')

# Elementwise sum; both produce the array
print (x + y)
print (np.add(x, y))

[[  5.   9.]
 [  7.  12.]]
[[  5.   9.]
 [  7.  12.]]


In [29]:
# Elementwise difference; both produce the array
print (x - y)
print (np.subtract(x, y))

[[ 3. -3.]
 [-3. -4.]]
[[ 3. -3.]
 [-3. -4.]]


In [30]:

# Elementwise product; both produce the array# Element 
print (x * y)
print (np.multiply(x, y))

[[  4.  18.]
 [ 10.  32.]]
[[  4.  18.]
 [ 10.  32.]]


To multiply matrix dot is available both as a function in the numpy module and as an instance method of array objects.

In [5]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(type(x))
# matrix product; both produce the same result
print(x.dot(y))
print(np.dot(x, y))

<class 'numpy.ndarray'>
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [33]:
#adding a scalar value
a = np.array([1, 2, 3, 4]) #create an array

a + 1

array([2, 3, 4, 5])

In [34]:
#finding square of each element

a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [26]:
#multiplication

c = np.diag([1, 2, 3, 4])

c*c

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

** Linear Algebra **

In [4]:
#inverse of a matrix
a = np.array([[1,2],[3,4]])
ainv = np.linalg.inv(a)
print(ainv)
print(ainv.dot(a))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[  1.00000000e+00   4.44089210e-16]
 [  0.00000000e+00   1.00000000e+00]]


In [14]:
# determinant of a matrix

np.linalg.det(a)

-4.0

In [18]:
#sum of diagonal element (trace of matrix)

print(np.diag(a).sum())
print(np.sum(np.diag(a)))

#Trace of a matrix
print(np.trace(a))

5
5
5


**2. Logical Operations**

In [28]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b)

array([ True,  True,  True, False], dtype=bool)

In [19]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

print(np.logical_and(a, b))
print(np.logical_not(a))
print(np.logical_xor(a,b))

[ True False False False]
[False False  True  True]
[False  True  True False]


**3. Transcendental functions:**

Examples of transcendental functions include the exponential function, the logarithm, and the trigonometric functions.

In [22]:
a1 = np.linspace(0,1,6)

np.sin(a1) 

array([ 0.        ,  0.19866933,  0.38941834,  0.56464247,  0.71735609,
        0.84147098])

In [25]:
np.cos(a1)

array([ 1.        ,  0.98006658,  0.92106099,  0.82533561,  0.69670671,
        0.54030231])

In [26]:
np.exp(a1)   #evaluates e^x for each element in a given input

array([ 1.        ,  1.22140276,  1.4918247 ,  1.8221188 ,  2.22554093,
        2.71828183])

# Basic Reductions

**computing sums**

In [32]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [10]:
#sum by rows and by columns

x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [11]:
x1 = np.sum(x, axis=0)
x1

array([3, 3])

In [13]:
x2 = np.sum(x, axis=1)
x2

array([2, 4])

In [14]:
x3= x.sum(axis=0)
x3

array([3, 3])

**Other reductions**

In [35]:
x = np.array([1, 3, 2])
x.min()

1

In [36]:
x.max()

3

In [37]:
x.argmin()     # index of minimum element

0

In [40]:
x.argmax()

1

# Array Shape Manipulation

**Flattening**

In [37]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel() #Return a contiguous flattened array. A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.

array([1, 2, 3, 4, 5, 6])

In [38]:
a.T #Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

**Reshaping**

The inverse operation to flattening:

In [34]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape

(2, 3)

In [6]:
b = a.ravel()
print(b)
print(b.shape)


[1 2 3 4 5 6]
(6,)


In [37]:
b = b.reshape([2, 3])
b


array([[1, 2, 3],
       [4, 5, 6]])

**Sorting Data**

In [38]:
#Sorting along an axis:
a = np.array([[5, 4, 6], [2, 3, 2]])
b = np.sort(a,axis=0)
print("a=\n",a)
print("b=\n",b)

a=
 [[5 4 6]
 [2 3 2]]
b=
 [[2 3 2]
 [5 4 6]]


In [39]:
#in-place sort
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [40]:
#Finding indexes of minima and maxima:
a = np.array([4, 3, 1, 2])
j_max = np.argmax(a)
j_min = np.argmin(a)
j_max,j_min

(0, 2)

In [41]:
#Task : Solving a linear System

# Ax = b

A = np.array([[1,2],[3,4]]) 
b = np.array([1,2])

x = np.linalg.inv(A).dot(b)
print(x)


[2.22044605e-16 5.00000000e-01]


In [42]:
#Another way to solve the linear system

x = np.linalg.solve(A,b)
print(x)

[0.  0.5]


In [52]:
import numpy as np
x=np.random.random(10)
print(x)

np.set_printoptions(precision=3)              #no of digits after the decimal point
print(x)

np.set_printoptions(suppress=True)            #Suppressing the scientific notation
print(x)

[0.543 0.253 0.234 0.958 0.737 0.295 0.819 0.278 0.909 0.744]
[0.543 0.253 0.234 0.958 0.737 0.295 0.819 0.278 0.909 0.744]
[0.543 0.253 0.234 0.958 0.737 0.295 0.819 0.278 0.909 0.744]


In [51]:
#Another way to create a 2D matrix

a = np.matrix([[1,2,3],[4,5,6]])
a
type(a)

numpy.matrixlib.defmatrix.matrix

In [46]:
a = np.array([[1,2,3],[4,5,6]])
a
type(a)

numpy.ndarray

In [2]:
import numpy as np
v = np.ones((10,10))
v[1:-1,1:-1] = 0
print(v)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
v = np.dot(np.ones((5,3)), np.ones((3,2)))
print(v)

#using matmul function
v=np.matmul(np.ones([5,3]),np.ones((3,2)))
print(v)

# Alternative solution, in Python 3.5 and above
v = np.ones((5,3)) @ np.ones((3,2))
print(v)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [17]:
v = np.arange(11)
v[(3 < v) & (v < 8)] *= -1
print(v)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
